# Generated by Django 3.2.18 on 2023-04-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallblog', '0002_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
